$projdir="C:\Dropbox\c#\labs\demoTest\DemoTests"
$output = "C:\Project\out\"
$msbuild = "c:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe" 
#Write-Host $msbuild "$projdir\DemoTests.sln" /T:""DemoTests"" "/property:Configuration=Release"
& $msbuild "DemoTests.sln" "/property:OutDir=$output\out\" "/property:Configuration=Release"
